# Generated by Django 5.2.10 on 2026-01-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True, verbose_name='帳單編號')),
                ('bill_date', models.DateField(verbose_name='帳單日期')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('partial', '部分付款'), ('paid', '已付款'), ('refunded', '已退款'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小計')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='折扣')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='總金額')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已付金額')),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='應付餘額')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '現金'), ('credit_card', '信用卡'), ('debit_card', '扣帳卡'), ('octopus', '八達通'), ('alipay', '支付寶'), ('wechat', '微信支付'), ('bank_transfer', '銀行轉帳'), ('account_balance', '帳戶餘額'), ('other', '其他')], max_length=20, verbose_name='付款方式')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '帳單',
                'verbose_name_plural': '帳單',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小計')),
            ],
            options={
                'verbose_name': '帳單項目',
                'verbose_name_plural': '帳單項目',
            },
        ),
        migrations.CreateModel(
            name='ChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='項目代碼')),
                ('name', models.CharField(max_length=100, verbose_name='項目名稱')),
                ('item_type', models.CharField(choices=[('registration', '掛號費'), ('consultation', '診金'), ('medicine', '藥費'), ('treatment', '治療費'), ('certificate', '證明書費'), ('other', '其他')], default='other', max_length=20, verbose_name='項目類型')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='預設價格')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '收費項目',
                'verbose_name_plural': '收費項目',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='原始欠款金額')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='剩餘欠款金額')),
                ('status', models.CharField(choices=[('outstanding', '未清'), ('partial', '部分清償'), ('cleared', '已清'), ('written_off', '已核銷')], default='outstanding', max_length=20, verbose_name='狀態')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '欠款記錄',
                'verbose_name_plural': '欠款記錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispensingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='訂單編號')),
                ('client_order_id', models.CharField(max_length=100, unique=True, verbose_name='客戶訂單 ID')),
                ('status', models.CharField(choices=[('pending', '待發送'), ('sent', '已發送'), ('confirmed', '對方已確認'), ('processing', '配藥中'), ('shipped', '已發貨'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('medicine_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='藥費')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='加工費')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='運送費')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='總金額')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='收件人姓名')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='收件人電話')),
                ('recipient_address', models.TextField(verbose_name='收件地址')),
                ('tracking_company', models.CharField(blank=True, max_length=50, verbose_name='物流公司')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='運單號碼')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name='API 回應')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='發送時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '派藥訂單',
                'verbose_name_plural': '派藥訂單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalPharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配藥房名稱')),
                ('pharmacy_type', models.CharField(choices=[('decoction', '煎藥房'), ('concentrate', '濃縮配藥房')], max_length=20, verbose_name='類型')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='加工費')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='運送費')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API 端點')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('webhook_api_key', models.CharField(blank=True, max_length=255, verbose_name='Webhook API Key')),
                ('api_request_format', models.JSONField(blank=True, null=True, verbose_name='API 請求格式範本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '外部配藥房',
                'verbose_name_plural': '外部配藥房',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金額')),
                ('payment_method', models.CharField(choices=[('cash', '現金'), ('credit_card', '信用卡'), ('debit_card', '扣帳卡'), ('octopus', '八達通'), ('alipay', '支付寶'), ('wechat', '微信支付'), ('bank_transfer', '銀行轉帳'), ('account_balance', '帳戶餘額'), ('other', '其他')], max_length=20, verbose_name='付款方式')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='參考編號')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='付款時間')),
            ],
            options={
                'verbose_name': '付款記錄',
                'verbose_name_plural': '付款記錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
