# Generated by Django 5.2.10 on 2026-01-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('consultation', '0001_initial'),
        ('patients', '0001_initial'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bills', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.patient', verbose_name='病患'),
        ),
        migrations.AddField(
            model_name='bill',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='registration.registration', verbose_name='掛號'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill', verbose_name='帳單'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='consultation.prescription', verbose_name='處方'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='charge_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='billing.chargeitem', verbose_name='收費項目'),
        ),
        migrations.AddField(
            model_name='debt',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='billing.bill', verbose_name='帳單'),
        ),
        migrations.AddField(
            model_name='debt',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='patients.patient', verbose_name='病患'),
        ),
        migrations.AddField(
            model_name='dispensingorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispensing_orders', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='dispensingorder',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_orders', to='consultation.prescription', verbose_name='處方'),
        ),
        migrations.AddField(
            model_name='dispensingorder',
            name='external_pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.externalpharmacy', verbose_name='外部配藥房'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.bill', verbose_name='帳單'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='收款人員'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_date', 'status'], name='billing_bil_bill_da_c59f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['patient', 'bill_date'], name='billing_bil_patient_bc4667_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensingorder',
            index=models.Index(fields=['status', 'created_at'], name='billing_dis_status_e60abb_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensingorder',
            index=models.Index(fields=['external_pharmacy', 'status'], name='billing_dis_externa_aeb0b1_idx'),
        ),
    ]
