# Generated by Django 5.2.10 on 2026-01-23 09:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='診間名稱')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='診間代碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '診間',
                'verbose_name_plural': '診間',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=100, verbose_name='診所名稱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='傳真')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/', verbose_name='診所標誌')),
                ('enable_data_masking', models.BooleanField(default=False, verbose_name='啟用資料遮罩')),
                ('appointment_slot_duration', models.PositiveIntegerField(default=15, verbose_name='預約時段長度（分鐘）')),
                ('auto_queue_mode', models.CharField(choices=[('auto_front', '自動排前'), ('manual', '助理手動調整'), ('doctor_choice', '醫師自由選擇')], default='manual', max_length=20, verbose_name='過號處理模式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '診所設定',
                'verbose_name_plural': '診所設定',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '系統管理員'), ('doctor', '醫師'), ('assistant', '助理')], default='assistant', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='聯絡電話')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='醫師證書號碼')),
                ('data_masking_enabled', models.BooleanField(default=False, verbose_name='啟用資料遮罩')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '刪除'), ('view', '查看')], max_length=20, verbose_name='操作類型')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名稱')),
                ('object_id', models.CharField(max_length=100, verbose_name='物件 ID')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='修改前資料')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='修改後資料')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
            ],
            options={
                'verbose_name': '稽核日誌',
                'verbose_name_plural': '稽核日誌',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '星期日'), (1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六')], verbose_name='星期')),
                ('period', models.CharField(choices=[('morning', '上午'), ('afternoon', '下午'), ('evening', '晚間')], max_length=20, verbose_name='時段')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('max_patients', models.PositiveIntegerField(default=30, verbose_name='最大看診人數')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='醫師')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.clinicroom', verbose_name='診間')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班',
                'ordering': ['day_of_week', 'period'],
                'unique_together': {('doctor', 'day_of_week', 'period')},
            },
        ),
    ]
