# Generated by Django 5.2.10 on 2026-01-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='藥品代碼')),
                ('name', models.CharField(max_length=100, verbose_name='藥品名稱')),
                ('english_name', models.CharField(blank=True, max_length=100, verbose_name='英文名稱')),
                ('pinyin', models.CharField(blank=True, max_length=100, verbose_name='拼音')),
                ('medicine_type', models.CharField(choices=[('herb', '中藥飲片'), ('concentrate', '濃縮中藥'), ('western', '西藥'), ('supplement', '保健品'), ('other', '其他')], default='concentrate', max_length=20, verbose_name='藥品類型')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='規格')),
                ('unit', models.CharField(default='克', max_length=20, verbose_name='單位')),
                ('package_unit', models.CharField(blank=True, max_length=20, verbose_name='包裝單位')),
                ('package_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='包裝數量')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本價')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='售價')),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='安全庫存量')),
                ('properties', models.TextField(blank=True, verbose_name='性味')),
                ('meridians', models.TextField(blank=True, verbose_name='歸經')),
                ('functions', models.TextField(blank=True, verbose_name='功效')),
                ('indications', models.TextField(blank=True, verbose_name='主治')),
                ('contraindications', models.TextField(blank=True, verbose_name='禁忌')),
                ('dosage_guide', models.TextField(blank=True, verbose_name='用量指引')),
                ('external_sku', models.CharField(blank=True, max_length=50, verbose_name='外部 SKU')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '藥品',
                'verbose_name_plural': '藥品',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供應商名稱')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='供應商代碼')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='傳真')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '供應商',
                'verbose_name_plural': '供應商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='庫存數量')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.medicine', verbose_name='藥品')),
            ],
            options={
                'verbose_name': '庫存',
                'verbose_name_plural': '庫存',
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分類名稱')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='分類代碼')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.medicinecategory', verbose_name='上層分類')),
            ],
            options={
                'verbose_name': '藥品分類',
                'verbose_name_plural': '藥品分類',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='inventory.medicinecategory', verbose_name='分類'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='進貨單號')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('received', '已收貨'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='狀態')),
                ('order_date', models.DateField(verbose_name='訂購日期')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='預計到貨日期')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='實際到貨日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='總金額')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '進貨單',
                'verbose_name_plural': '進貨單',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小計')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已收數量')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.medicine', verbose_name='藥品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='進貨單')),
            ],
            options={
                'verbose_name': '進貨單項目',
                'verbose_name_plural': '進貨單項目',
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='inventory.supplier', verbose_name='供應商'),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', '進貨'), ('dispense', '配藥扣減'), ('adjustment', '盤點調整'), ('return', '退貨'), ('damage', '損耗'), ('transfer', '調撥')], max_length=20, verbose_name='異動類型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='數量')),
                ('before_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='異動前數量')),
                ('after_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='異動後數量')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='單位成本')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='參考編號')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.medicine', verbose_name='藥品')),
            ],
            options={
                'verbose_name': '庫存異動',
                'verbose_name_plural': '庫存異動',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['medicine', 'created_at'], name='inventory_i_medicin_9e5dd2_idx'), models.Index(fields=['transaction_type', 'created_at'], name='inventory_i_transac_1f1168_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompoundFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='比例')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('compound_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_formulas', to='inventory.medicine', verbose_name='複方藥品')),
                ('ingredient_medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_ingredient_in', to='inventory.medicine', verbose_name='成份藥品')),
            ],
            options={
                'verbose_name': '複方成份',
                'verbose_name_plural': '複方成份',
                'unique_together': {('compound_medicine', 'ingredient_medicine')},
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['code'], name='inventory_m_code_7c5b57_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='inventory_m_name_7f2fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['pinyin'], name='inventory_m_pinyin_17ac23_idx'),
        ),
    ]
