# Generated by Django 5.2.10 on 2026-01-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='報表名稱')),
                ('report_type', models.CharField(choices=[('daily_summary', '每日結算報表'), ('monthly_summary', '月結報表'), ('doctor_workload', '醫師工作量統計'), ('medicine_usage', '藥品使用統計'), ('patient_visit', '病患就診統計'), ('revenue', '營收報表'), ('inventory', '庫存報表'), ('external_pharmacy', '外部配藥房對帳'), ('custom', '自訂報表')], max_length=30, verbose_name='報表類型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('query_template', models.TextField(blank=True, verbose_name='查詢範本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '報表範本',
                'verbose_name_plural': '報表範本',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='報表名稱')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='查詢參數')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='報表資料')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='報表檔案')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成時間')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='生成者')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reporttemplate', verbose_name='報表範本')),
            ],
            options={
                'verbose_name': '已生成報表',
                'verbose_name_plural': '已生成報表',
                'ordering': ['-generated_at'],
            },
        ),
    ]
