# Generated by Django 5.2.10 on 2026-01-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='預約日期')),
                ('appointment_time', models.TimeField(verbose_name='預約時間')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='狀態')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='醫師')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='病患')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.clinicroom', verbose_name='診間')),
            ],
            options={
                'verbose_name': '預約',
                'verbose_name_plural': '預約',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='掛號號碼')),
                ('queue_number', models.PositiveIntegerField(verbose_name='候診號碼')),
                ('visit_type', models.CharField(choices=[('first_visit', '初診'), ('follow_up', '覆診')], default='follow_up', max_length=20, verbose_name='就診類型')),
                ('status', models.CharField(choices=[('waiting', '候診中'), ('in_consultation', '看診中'), ('completed', '已完成'), ('cancelled', '已取消'), ('no_show', '過號')], default='waiting', max_length=20, verbose_name='狀態')),
                ('registration_date', models.DateField(verbose_name='掛號日期')),
                ('registration_time', models.TimeField(auto_now_add=True, verbose_name='掛號時間')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='報到時間')),
                ('consultation_start_time', models.DateTimeField(blank=True, null=True, verbose_name='看診開始時間')),
                ('consultation_end_time', models.DateTimeField(blank=True, null=True, verbose_name='看診結束時間')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='掛號費')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='registration.appointment', verbose_name='關聯預約')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registrations', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='醫師')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='patients.patient', verbose_name='病患')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='core.clinicroom', verbose_name='診間')),
            ],
            options={
                'verbose_name': '掛號',
                'verbose_name_plural': '掛號',
                'ordering': ['registration_date', 'queue_number'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'doctor'], name='registratio_appoint_2d0ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_date'], name='registratio_patient_578af1_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['registration_date', 'doctor'], name='registratio_registr_89e8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['patient', 'registration_date'], name='registratio_patient_13ca40_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status'], name='registratio_status_76ed6e_idx'),
        ),
    ]
