# Generated by Django 5.2.10 on 2026-01-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_number', models.CharField(max_length=20, unique=True, verbose_name='病歷號碼')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性別')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('id_card_number', models.CharField(blank=True, max_length=20, verbose_name='身份證號碼')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='手機')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='緊急聯絡人姓名')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='緊急聯絡人電話')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='與病患關係')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='血型')),
                ('allergies', models.TextField(blank=True, verbose_name='過敏史')),
                ('medical_history', models.TextField(blank=True, verbose_name='病史')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='帳戶餘額')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '病患',
                'verbose_name_plural': '病患',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('tongue', '舌診'), ('face', '面診'), ('other', '其他')], default='other', max_length=20, verbose_name='影像類型')),
                ('image', models.ImageField(upload_to='patient_images/%Y/%m/', verbose_name='影像檔案')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='拍攝時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_patient_images', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patients.patient', verbose_name='病患')),
            ],
            options={
                'verbose_name': '病患影像',
                'verbose_name_plural': '病患影像',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['chart_number'], name='patients_pa_chart_n_33d3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='patients_pa_name_8d04ea_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['id_card_number'], name='patients_pa_id_card_528c0c_idx'),
        ),
    ]
