# Generated by Django 5.2.10 on 2026-01-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('medical', '診斷證明書'), ('sick_leave', '病假證明書'), ('referral', '轉介信'), ('other', '其他')], max_length=20, verbose_name='證明書類型')),
                ('certificate_number', models.CharField(max_length=20, unique=True, verbose_name='證明書編號')),
                ('content', models.TextField(verbose_name='內容')),
                ('issue_date', models.DateField(verbose_name='開立日期')),
                ('sick_leave_start', models.DateField(blank=True, null=True, verbose_name='病假開始日期')),
                ('sick_leave_end', models.DateField(blank=True, null=True, verbose_name='病假結束日期')),
                ('print_count', models.PositiveIntegerField(default=0, verbose_name='列印次數')),
                ('last_printed_at', models.DateTimeField(blank=True, null=True, verbose_name='最後列印時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '證明書',
                'verbose_name_plural': '證明書',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='主訴')),
                ('present_illness', models.TextField(blank=True, verbose_name='現病史')),
                ('past_history', models.TextField(blank=True, verbose_name='既往史')),
                ('inspection', models.TextField(blank=True, verbose_name='望診')),
                ('tongue_appearance', models.TextField(blank=True, verbose_name='舌象')),
                ('listening_smelling', models.TextField(blank=True, verbose_name='聞診')),
                ('inquiry', models.TextField(blank=True, verbose_name='問診')),
                ('pulse', models.TextField(blank=True, verbose_name='脈象')),
                ('palpation', models.TextField(blank=True, verbose_name='觸診')),
                ('tcm_diagnosis', models.TextField(blank=True, verbose_name='中醫診斷')),
                ('western_diagnosis', models.TextField(blank=True, verbose_name='西醫診斷')),
                ('syndrome_differentiation', models.TextField(blank=True, verbose_name='辨證')),
                ('treatment_principle', models.TextField(blank=True, verbose_name='治則')),
                ('advice', models.TextField(blank=True, verbose_name='醫囑')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='覆診日期')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '診療記錄',
                'verbose_name_plural': '診療記錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('chief_complaint', '主訴'), ('symptom', '症狀'), ('tongue', '舌象'), ('pulse', '脈象'), ('diagnosis', '診斷'), ('treatment', '治則')], max_length=20, verbose_name='類別')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='代碼')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '辨證詞庫',
                'verbose_name_plural': '辨證詞庫',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='方名')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分類')),
                ('indication', models.TextField(blank=True, verbose_name='適應症')),
                ('usage_instruction', models.TextField(blank=True, verbose_name='服用方法')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '經驗方',
                'verbose_name_plural': '經驗方',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceFormulaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='劑量')),
                ('unit', models.CharField(default='克', max_length=20, verbose_name='單位')),
                ('decoction_method', models.CharField(blank=True, max_length=20, verbose_name='煎煮方式')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '經驗方項目',
                'verbose_name_plural': '經驗方項目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(max_length=20, unique=True, verbose_name='處方編號')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='處方名稱')),
                ('total_doses', models.PositiveIntegerField(default=1, verbose_name='總劑數')),
                ('doses_per_day', models.PositiveIntegerField(default=1, verbose_name='每日劑數')),
                ('days', models.PositiveIntegerField(default=1, verbose_name='天數')),
                ('usage_instruction', models.TextField(blank=True, verbose_name='服用方法')),
                ('dispensing_method', models.CharField(choices=[('internal', '內部配藥'), ('external_decoction', '外送煎藥'), ('external_concentrate', '外送濃縮')], default='internal', max_length=30, verbose_name='執藥方式')),
                ('medicine_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='藥費')),
                ('is_dispensed', models.BooleanField(default=False, verbose_name='是否已配藥')),
                ('dispensed_at', models.DateTimeField(blank=True, null=True, verbose_name='配藥時間')),
                ('audit_log', models.JSONField(blank=True, null=True, verbose_name='修改記錄')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '處方',
                'verbose_name_plural': '處方',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='劑量')),
                ('unit', models.CharField(default='克', max_length=20, verbose_name='單位')),
                ('decoction_method', models.CharField(blank=True, max_length=20, verbose_name='煎煮方式')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='單價')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='小計')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '處方項目',
                'verbose_name_plural': '處方項目',
                'ordering': ['id'],
            },
        ),
    ]
