# Generated by Django 5.2.10 on 2026-01-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('consultation', '0001_initial'),
        ('inventory', '0001_initial'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='醫師'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='registration.registration', verbose_name='掛號'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='consultation.consultation', verbose_name='診療記錄'),
        ),
        migrations.AddIndex(
            model_name='diagnosticterm',
            index=models.Index(fields=['category', 'name'], name='consultatio_categor_839531_idx'),
        ),
        migrations.AddField(
            model_name='experienceformula',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='experience_formulas', to=settings.AUTH_USER_MODEL, verbose_name='醫師'),
        ),
        migrations.AddField(
            model_name='experienceformulaitem',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultation.experienceformula', verbose_name='經驗方'),
        ),
        migrations.AddField(
            model_name='experienceformulaitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_formula_items', to='inventory.medicine', verbose_name='藥品'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultation.consultation', verbose_name='診療記錄'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='external_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='billing.externalpharmacy', verbose_name='外部配藥房'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='inventory.medicine', verbose_name='藥品'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultation.prescription', verbose_name='處方'),
        ),
    ]
